### ISSUE TITLE
Measurement code?

### ISSUE THREAD

**Issue by liuyonggen** [yassineazimani/SnapAds4J#35]
where is the Measurement code? thank you .

**Comment by yassineazimani** [comment]
@liuyonggen What are you talking about ? If you talk about coverage code, the link is present in README.MD : 

https://coveralls.io/github/yassineazimani/SnapAds4J?branch=develop

**Comment by liuyonggen** [comment]
I mean Your code does not contain this： https://developers.snapchat.com/api/docs/?shell#measurement；

can you commit this（https://developers.snapchat.com/api/docs/?shell#measurement） part？thank you。

**Comment by yassineazimani** [comment]
@liuyonggen 

Check https://github.com/yassineazimani/SnapAds4J/blob/develop/src/main/java/snapads4j/stats/SnapStats.java 

It would be answer at your needs. If it's not, i'll update the missing part.

Best regards,

**Comment by liuyonggen** [comment]
### method 【getAdAccountStats(ags****)】
 This method only supports returning a single object;
Can you support returning List<TimeSerieStat> of all AdSquadStats according to account id.

e.g.：List<TimeSerieStat> getAdAccountStats(ags****){
       
    }

**Comment by yassineazimani** [comment]
@liuyonggen I'll handle it

**Comment by liuyonggen** [comment]
I wait for you @yassineazimani

**Comment by liuyonggen** [comment]
> @liuyonggen I'll handle it

Best to support page turning function

**Comment by liuyonggen** [comment]
> @liuyonggen I'll handle it

Best to support page turning function @yassineazimani

**Comment by yassineazimani** [comment]
@liuyonggen Pagination ?

**Comment by liuyonggen** [comment]
> @liuyonggen Pagination ?

https://developers.snapchat.com/api/docs/?shell#pagination229 @yassineazimani

**Comment by yassineazimani** [comment]
@liuyonggen I know what is pagination, i don't need API documentation. I'll handle it.

 **Next time : Just explain/clarify well your need.**

**Comment by liuyonggen** [comment]
When can it be ok？
